### 1. IMPORT DEPENDENCIES

In [1]:
!pip3 install 'stable-baselines3[extra]'

  Using cached rich-13.7.1-py3-none-any.whl (240 kB)
  Using cached Shimmy-1.3.0-py3-none-any.whl (37 kB)
  Using cached AutoROM-0.6.1-py3-none-any.whl (9.4 kB)
  Using cached AutoROM.accept-rom-license-0.6.1.tar.gz (434 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 2.4 MB/s eta 0:00:0000:0100:010m


  Created wheel for AutoROM.accept-rom-license: filename=AutoROM.accept_rom_license-0.6.1-py3-none-any.whl size=446660 sha256=0aae213a82d5b430dc3b762d8df20662795336586ff41b1721cbc271d5096e9d
  Stored in directory: /Users/vinayakcm/Library/Caches/pip/wheels/bc/fc/c6/8aa657c0d2089982f2dabd110efc68c61eb49831fdb7397351
Successfully built AutoROM.accept-rom-license
  Attempting uninstall: shimmy
    Found existing installation: Shimmy 2.0.0
    Uninstalling Shimmy-2.0.0:
      Successfully uninstalled Shimmy-2.0.0
  Attempting uninstall: ale-py
    Found existing installation: ale-py 0.9.1
    Uninstalling ale-py-0.9.1:
      Successfully uninstalled ale-py-0.9.1


In [2]:
import gymnasium as gym 
import numpy as np
import os
from stable_baselines3 import PPO
from stable_baselines3 import DQN
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy #Average reward, Standard deviation 

2024-08-13 23:53:42.508439: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


### 2. LOAD ENVIRONMENT

In [3]:
environment_name = "CartPole-v1"
env = gym.make(environment_name, render_mode = "human")

In [3]:
episodes = 15
for episode in range(1, episodes+1):
    state = env.reset()
    done = False
    score = 0 
    
    while not done:
        env.render()
        action = env.action_space.sample()
        obs, reward, done, truncated, info = env.step(action)
        score+=reward
    print('Episode:{} Score:{}'.format(episode, score))


Episode:1 Score:22.0
Episode:2 Score:22.0
Episode:3 Score:23.0
Episode:4 Score:29.0
Episode:5 Score:14.0
Episode:6 Score:14.0
Episode:7 Score:41.0
Episode:8 Score:9.0
Episode:9 Score:40.0
Episode:10 Score:23.0
Episode:11 Score:13.0
Episode:12 Score:34.0
Episode:13 Score:17.0
Episode:14 Score:17.0
Episode:15 Score:13.0


In [20]:
env.step(action)

/Users/vinayak/anaconda3/lib/python3.11/site-packages/gymnasium/envs/classic_control/cartpole.py:180: UserWarning: WARN: You are calling 'step()' even though this environment has already returned terminated = True. You should always call 'reset()' once you receive 'terminated = True' -- any further steps are undefined behavior.
  logger.warn(


(array([-0.15693821,  0.41432214,  0.21812518, -0.06763028], dtype=float32),
 0.0,
 True,
 False,
 {})

In [11]:
env.close()

In [ ]:
env.reset()

In [ ]:
env.step(1)

### 3. UNDERSTANDING THE ENVIRONMENT

In [ ]:
#1.         2.
#Push left, Push right [0,1]

env.action_space 

In [ ]:
env.action_space.sample()

In [ ]:
# 1.             2.             3.          4.
#Cart position, Cart velocity, Pole angle, Pole angular velocity

env.observation_space

In [ ]:
env.observation_space.sample()

### 4. TRAIN AN RL AGENT

In [4]:
#Training log data is stored in log_path
log_path = os.path.join("/Users/vinayak/Documents/Machine Learning Projects/Reinforcement Learning/Projects/CartPole/Training/Saved Models")
log_path

'/Users/vinayak/Documents/Machine Learning Projects/Reinforcement Learning/Projects/CartPole/Training/Saved Models'

In [4]:
#Creating the dummy vector env only
env = gym.make(environment_name)
env = DummyVecEnv([lambda: env])
model = PPO("MlpPolicy", env, verbose = 1, tensorboard_log = log_path)
#MLP - multilayer perceptron is used to generate policy
#Verbose - Level of data you need shown

Using cpu device


In [5]:
#Training the Agent
model.learn(total_timesteps = 20000)

Logging to /Users/vinayak/Documents/Machine Learning Projects/Reinforcement Learning/Training/Logs/PPO_16
-----------------------------
| time/              |      |
|    fps             | 7794 |
|    iterations      | 1    |
|    time_elapsed    | 0    |
|    total_timesteps | 2048 |
-----------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 5400         |
|    iterations           | 2            |
|    time_elapsed         | 0            |
|    total_timesteps      | 4096         |
| train/                  |              |
|    approx_kl            | 0.0083151385 |
|    clip_fraction        | 0.105        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.686       |
|    explained_variance   | 0.00139      |
|    learning_rate        | 0.0003       |
|    loss                 | 6.87         |
|    n_updates            | 10           |
|    policy_gradient_loss | -0.0179    

### 5. SAVE AND RELOAD MODEL

In [5]:
PPO_Path = os.path.join("/Users/vinayak/Documents/Machine Learning Projects/Reinforcement Learning/Projects/CartPole/Training/Saved Models/best_model.zip")

In [21]:
model.save(PPO_Path)

In [ ]:
del model

In [6]:
model = PPO.load(PPO_Path, env=env)

# 5. EVALUATION

In [14]:
evaluate_policy(model, env, n_eval_episodes = 10, render = True)

(500.0, 0.0)

### 6. TESTING MODEL

In [18]:
episodes = 5
for episode in range(1, episodes + 1):
    #Prevoius episode data of cart velocity and reseting game to 0
    obs = env.reset()  # Removed [0] indexing
    done = False
    score = 0
    
    while not done:
        #Displaying the env
        env.render()
        
        #model.predict(obs): predicts what action to be taken based on obs and stores 2 output values(action & None)
        action, _states = model.predict(obs)
        
        #env.step(action): takes the action needed and stores the observation in the variables
        obs, reward, done, info = env.step(action)
        #Updates score and episode only get over when score = 500
        score += reward
        
    print("Episode: {}, Score: {}".format(episode, score))

Episode: 1, Score: [185.]
Episode: 2, Score: [500.]
Episode: 3, Score: [344.]
Episode: 4, Score: [500.]
Episode: 5, Score: [477.]


In [16]:
env.step(action)

(array([[-0.02316703,  0.18071677,  0.01636625, -0.2800344 ]],
       dtype=float32),
 array([1.], dtype=float32),
 array([False]),
 [{'TimeLimit.truncated': False}])

In [15]:
env.reset()

array([[-0.02407388, -0.0469155 ,  0.01582326, -0.02342252]],
      dtype=float32)

In [32]:
model.predict(obs)

(array(1), None)

In [14]:
env.step(action)

(array([[ 0.03352444,  0.35671315, -0.00439783, -0.56456494]],
       dtype=float32),
 array([1.], dtype=float32),
 array([False]),
 [{'TimeLimit.truncated': False}])

### 7. VIEWING LOGS IN TENSORBOARD

In [17]:
#Just storing one of the training log PPO path into a variable
training_log_path = os.path.join(log_path, '/Users/vinayak/Documents/Machine Learning Projects/Reinforcement Learning/Training/Logs/PPO_16')

In [11]:
training_log_path

'/Users/vinayak/Documents/Machine Learning Projects/Reinforcement Learning/Training/Logs/PPO_16'

In [18]:
# Typing "!" at the beginning of a cell in jupyter notebook allows us to access terminal and directly type command line prompts to it.
#This cell allows us to access the training metrics of the agent using tensorflow
!tensorboard --logdir="{training_log_path}"

Serving TensorBoard on localhost; to expose to the network, use a proxy or pass --bind_all
TensorBoard 2.15.1 at http://localhost:6006/ (Press CTRL+C to quit)
^C


In [ ]:
# CORE METRICS TO LOOK FOR:
# 1. Average reward
# 2. Average episode length

# TRAINING STRATEGIES
# 1. Training for longer
# 2. Hyperparameter tunining
# 3. Try different algorithms

### APPLYING CALLBACKS TO TRAINING STAGE

In [19]:
# Here, we'll recreate the model with specified reward thresholds, so that the model with stop training 
# at a certain benchmarks

In [34]:
from stable_baselines3.common.callbacks import EvalCallback, StopTrainingOnRewardThreshold

In [35]:
#This is the place we want to save the best model which we'll find using call backs
save_path = os.path.join('Training', 'Saved Models')

In [36]:
# ---Setting up callbacks


#This call back is going to be the one which stops the training when a certain threshold is reached.
#Here the threshold is 200/500. 

stop_callback = StopTrainingOnRewardThreshold( reward_threshold=500, verbose=1 )

#This call back is going to be the one which will be triggered after each training round.
'''
COMMENT:
Here, we pass through:
    'env': environment
    'callback_on_new_best = stop_callback': Everytime there is a new best model, it's gonna run stop_callback and if the stop_callback realises the reward is above the threshold it'll stop the training
    'eval_freq': How frequently we wanna call the eval_callback
    'best_model': This is going to be the best model we get from the call backs
'''
eval_callback = EvalCallback(env,
                            callback_on_new_best = stop_callback,
                            eval_freq = 10000,
                            best_model_save_path = save_path,
                            verbose = 1)

In [37]:
#Creating a new PPO Model and assign these call backs
model = PPO('MlpPolicy', env, verbose = 1, tensorboard_log = log_path)

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [38]:
#eval_callback is going to be the callback that checks every 10000 timesteps and save a best_new_model and check if reward is past the threshhold
model.learn(total_timesteps = 20000, callback = eval_callback)

Logging to /Users/vinayak/Documents/Machine Learning Projects/Reinforcement Learning/Training/Logs/PPO_18
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 22       |
|    ep_rew_mean     | 22       |
| time/              |          |
|    fps             | 45       |
|    iterations      | 1        |
|    time_elapsed    | 44       |
|    total_timesteps | 2048     |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 27.3        |
|    ep_rew_mean          | 27.3        |
| time/                   |             |
|    fps                  | 45          |
|    iterations           | 2           |
|    time_elapsed         | 89          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.009529809 |
|    clip_fraction        | 0.098       |
|    clip_range           | 0.2         |
|    ent

New best mean reward!
Stopping training because the mean reward 500.00  is above the threshold 500


In [39]:
# Basically, we use the callback library to stop the training when the agent can play perfectly well to reach
# the max high score of 500. We automate it that way, which helps to not overtrain the model.

### CHANGING POLICIES

In [40]:
#This is an example of specifying a different architecture used for in the neural networks used in PPO

In [43]:
net_arch = [dict(pi = [128, 128, 128, 128], vf = [128, 128, 128, 128])]

In [44]:
model = PPO('MlpPolicy', env, verbose = 1, tensorboard_log = log_path, policy_kwargs = {'net_arch': net_arch})

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


/Users/vinayak/anaconda3/lib/python3.11/site-packages/stable_baselines3/common/policies.py:484: UserWarning: As shared layers in the mlp_extractor are removed since SB3 v1.8.0, you should now pass directly a dictionary and not a list (net_arch=dict(pi=..., vf=...) instead of net_arch=[dict(pi=..., vf=...)])
  warnings.warn(


In [45]:
model.learn(total_timesteps = 20000, callback = eval_callback)

Logging to /Users/vinayak/Documents/Machine Learning Projects/Reinforcement Learning/Training/Logs/PPO_19
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 20.2     |
|    ep_rew_mean     | 20.2     |
| time/              |          |
|    fps             | 42       |
|    iterations      | 1        |
|    time_elapsed    | 47       |
|    total_timesteps | 2048     |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 27.3        |
|    ep_rew_mean          | 27.3        |
| time/                   |             |
|    fps                  | 43          |
|    iterations           | 2           |
|    time_elapsed         | 93          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.014722402 |
|    clip_fraction        | 0.23        |
|    clip_range           | 0.2         |
|    ent

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 155      |
|    ep_rew_mean     | 155      |
| time/              |          |
|    fps             | 39       |
|    iterations      | 10       |
|    time_elapsed    | 521      |
|    total_timesteps | 20480    |
---------------------------------


### USING AN ALTERNATE ALGORITHM

In [46]:
#Rather than using a PPO model algorithm, we could use a DQN model algorithm

In [48]:
from stable_baselines3 import DQN

In [49]:
model = DQN('MlpPolicy', env, verbose = 1, tensorboard_log = log_path)

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [ ]:
model.learn(total_timesteps = 20000)